//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdKontra
    {
        public int NIP { get; set; }
        public string NazwaProduktu { get; set; }
        public string Opis { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public Nullable<decimal> CenaNetto { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<decimal> CenaBrutto { get { return CenaBrutto = CenaNetto * (1 + (Convert.ToDecimal(VAT) / 100)); } set {; } }
    }
}
